package com.parllay.util;

/**
 * Created by dushujian on 14-8-23.
 */
public class Constants {
    public static final String[] fromUsers ={"oiectuA5sWoebOoR1Fzlfe2ba2uw",
                                            "oiectuAIKhhyWTBa0v4PrB-RBbvw",
                                            "oiectuAObI9SuAn604rR15P470SE",
                                            "oiectuAQiZGpGBYDMvURmkKczh-U",
                                            "oiectuAS_2vwKI9308RFI3lTqrS8",
                                            "oiectuAb3Qh_9dqT62FzXv5Lhj6c",
                                            "oiectuAbKxgZJg6ovZzOajv-Z2eY",
                                            "oiectuAhRfuusnHiJdfijgWsMMg8",
                                            "oiectuAoK0_pbZnztFsety5exDwc",
                                            "oiectuAuPcWLY8V59REzvjahCrhg",
                                            "oiectuBWZ4As2zBiTb9-2o3gcmjQ",
                                            "oiectuC-7pFyMLKSza4etyqMskRI",
                                            "oiectuC4Up8Sa0pSiKdPLPNlidRQ",
                                            "oiectuCBicE8fqMyfwTUeYi9mn1o",
                                            "oiectuCFzUC6-Dv64qLE2CslO1f4",
                                            "oiectuCIHFD7K-Ybos6Z6SCq9A34",
                                            "oiectuCIXG0gFqLU47fjvdkZ-qc8",
                                            "oiectuCNGtCinyx6Vy5-53TvJev0",
                                            "oiectuC_VuVzDTuNZ6B7BOdl7XMA",
                                            "oiectuCd3W5GyQ1HBxyaVWICUbhA",
                                            "oiectuCdJbEiOq0KZaikTrULYWLI",
                                            "oiectuClSBDq9nSf5Q6s4TPuC2ts",
                                            "oiectuCn9UTCXXYTjipZanaTWCcY",
                                            "oiectuCqa57fe0LkxLsHDZ528hSw",
                                            "oiectuD2SlxpyIO30eQ2ztNFMxRE",
                                            "oiectuD4cP_jEAIlvSWy1mkPHgHY",
                                            "oiectuDHGXK87XktSPsODKIFjnok",
                                            "oiectuD_708jg3QKYPnAwGW0CGUc",
                                            "oiectuDeOiQ8Pe0Z01-mayQpgjnk",
                                            "oiectuDi3ISVWLPKpzsRtrvyzbOM",
                                            "oiectuDzCIqcMDg9IB74OQ3iD0Dg",
                                            "oiectuE31uvxgGNrpJFq6axIEK8Q",
                                            "oiectuE5F2xqVH-mDTzN9FBp6JJI",
                                            "oiectuEAs1_ewe1lE_GoyX1JMaBQ",
                                            "oiectuEFaaTOoO1HWXS7p5x7xfSw",
                                            "oiectuEIN4Cc-_cEPvsFQh5UCjAI",
                                            "oiectuEKCeR-Xmo99oirGPWnc5OI",
                                            "oiectuEhigaBMd_A5lz_e3Uhj4KQ",
                                            "oiectuExk5bJZyr4KehcFwcsWh-E",
                                            "oiectuF0v64b7ky6PcLV1mCDNrJ4",
                                            "oiectuFD0fSOvL9SF2t4BNbNAw8k",
                                            "oiectuFGm-orgpajTmKKWDKMpQbw",
                                            "oiectuFOVM3euiaT0WqfWnFg6Pk0",
                                            "oiectuFS39ydD76yXLGTp9ZVo0ik",
                                            "oiectuFWaJLNypLbC6dujBE7PaRg",
                                            "oiectuFc4tPzI0t3kUn95w0rC0W4",
                                            "oiectuFiGiz_9uAPQu51JrEm2Ts4",
                                            "oiectuFvj58_DHgMPPWlwGjbeYXY",
                                            "oiectuGBWJUDNSCwVpCrLnD8O9aQ",
                                            "oiectuGDVtzqyFPfXq-TDA5jtiMo",
                                            "oiectuGMY4ets2L0ocLkyhwZ3tjs",
                                            "oiectuGNZlv1n2MTq8xHoDvfNrIM",
                                            "oiectuGP0uM3fLbcxyjFbU1h6wL4",
                                            "oiectuGVo2jG2kJKPAEqWrE_huA4",
                                            "oiectuHBu6xVzXvjumibvvjWYRus",
                                            "oiectuHUfeQ_AKbcwRxiakGIHUss",
                                            "oiectuHVCzyYFkePRF_RSYTCxX1E",
                                            "oiectuHm4oJ6NtiWCNKp0bD7CjN0",
                                            "oiectuI0NwJSVg9R61kglX_46-ZM",
                                            "oiectuIBWx1BGuNXnKTwQ2WBj0Xk",
                                    };
    public static final String[] ClickEventKeys = {"EventKey_01","EventKey_02","EventKey_03"};

    public static final String[] ViewEventKeys = {"www.parllay.cn","www.baidu.com","www.sina.com.cn","www.qq.com","www.sohu.com"};
}
